static_presets = [
    {'name': 'Generation (TWh)', 'sheet_name':'gen', 'result': 'Generation National (TWh)', 'preset': 'Stacked Bars'},
    {'name': 'Capacity (GW)', 'sheet_name':'cap', 'result': 'Capacity National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'New Annual Capacity (GW)', 'sheet_name':'cap_new_ann', 'result': 'New Annual Capacity National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Annual Retirements (GW)', 'sheet_name':'retire_ann', 'result': 'Annual Retirements National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Final Gen by timeslice (GW)', 'sheet_name':'gen_final_timeslice', 'result': 'Gen by timeslice national (GW)', 'preset': 'Stacked Bars Final'},
    {'name': 'Bulk System Electricity Price ($/MWh)', 'sheet_name':'elec_price', 'result': 'Requirement Prices and Quantities National Annual', 'preset': 'Bulk System Electricity Price ($/MWh)'},
    {'name': 'Bulk System Electricity Price by State ($/MWh)', 'sheet_name':'elec_price_st', 'result': 'Requirement Prices and Quantities BA Annual', 'preset': 'Bulk System Electricity Price by State ($/MWh)', 'config': {'sync_axes':'No'}},
    {'name': 'Total Bulk System Electricity Price by State, final year ($/MWh)', 'sheet_name':'elec_price_st_map', 'result': 'Requirement Prices and Quantities BA Annual', 'preset': 'Total Bulk System Electricity Price State Map Final ($/MWh)'},
    {'name': 'Retail rate (¢/kWh)', 'sheet_name':'retail_rate', 'result': 'Retail rate (¢/kWh)', 'preset': 'Scenario Lines'},
    {'name': 'Retail rate by state (¢/kWh)', 'sheet_name':'retail_rate_st', 'result': 'Retail rate by state (¢/kWh)', 'preset': 'State Lines', 'config': {'sync_axes':'No'}},
    {'name': 'Retail rate by state, final year (¢/kWh)', 'sheet_name':'retail_rate_st_map', 'result': 'Retail rate by state (¢/kWh)', 'preset': 'State Map Final'},
    {'name': 'System Cost of Electricity ($/MWh)', 'sheet_name':'scoe', 'result': 'National Average Electricity Cost, model years ($/MWh)', 'preset': 'Scenario Lines'},
    {'name': 'System Cost of Electricity by Category ($/MWh)', 'sheet_name':'scoe_by_cat', 'result': 'National Average Electricity Cost, model years ($/MWh)', 'preset': 'Average Electricity Cost by Year ($/MWh)'},
    {'name': 'Present Value of System Cost through 2050 (Bil $)', 'sheet_name':'sys_cost', 'result': 'Sys Cost Annualized (Bil $)', 'preset': 'Discounted through 2050'},
    {'name': 'Total Transmission Capacity (TW-mi)', 'sheet_name':'trans_twmi', 'result': 'Transmission (GW-mi)', 'preset': 'Transmission Capacity Agg by type (TW-mi)'},
    {'name': 'Long-distance Transmission Capacity (TW-mi)', 'sheet_name':'trans_longdist', 'result': 'Transmission (GW-mi)', 'preset': 'Long-distance Transmission (TW-mi)'},
    {'name': 'Interregional Transmission Capacity (GW)', 'sheet_name':'trans_interreg', 'result': 'Interregional Transmission Capacity (GW)', 'preset': 'Scenario Lines'},
    {'name': 'Interconnection-Crossing Transmission Capacity (GW)', 'sheet_name':'trans_seam', 'result': 'Interconnection-Crossing Transmission Capacity (GW)', 'preset': 'Scenario Lines'},
    {'name': 'Emissions National (metric tons)', 'sheet_name':'emissions', 'result': 'Emissions National (metric tons)', 'preset': 'Scenario Lines Over Time'},
    {'name': 'Runtime (hours)', 'sheet_name':'runtime', 'result': 'Runtime', 'preset': 'Stacked Bars'},
]
